name: CI/CD Orderly

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies (frontend)
      run: |
        cd frontend
        npm install
        npm run build

    - name: Install dependencies (backend)
      run: |
        cd backend
        composer install
        php bin/console cache:clear